FORMAT: 1A
HOST: http://company-api.apiblueprint.org/

# company-api

Company-api is a simple API allowing consumers to view companies

## Companies Collection [/companies]

### List All companies [GET]

+ Response 200 (application/json)

        [
            {
                "name": "poltek tegal",
                "total_employee": 200,
                "address": "tegal",
                "country": "indonesia"
            }
        ]

### Create a New company [POST]

You may create your own company using this action. It takes a JSON
object containing parameter to create company

+ Request (application/json)


            {
                "name": "poltek tegal",
                "total_employee": 200,
                "address": "tegal",
                "country": "indonesia"
            }

+ Response 201 (application/json)

    + Headers

            Location: /companies/2

    + Body


            {
                "name": "poltek tegal",
                "total_employee": 200,
                "address": "tegal",
                "country": "indonesia"
            }